=== BitFis/advanced-mobile-dev-fin/ex2/app/src/main/assets/openweather_api_forcast_1-0-0.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://api.openweathermap.org/forcast",
  "type": "object",
  "title": "Forcast Schema",
  "required": [
    "cod",
    "message",
    "cnt",
    "list",
    "city"
  ],
  "properties": {
    "cod": {
      "$id": "#/properties/cod",
      "type": "string",
      "title": "The Cod Schema",
      "default": "",
      "examples": [
        "200"
      ],
      "pattern": "^(.*)$"
    },
    "message": {
      "$id": "#/properties/message",
      "type": "integer",
      "title": "The Message Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "cnt": {
      "$id": "#/properties/cnt",
      "type": "integer",
      "title": "The Cnt Schema",
      "default": 0,
      "examples": [
        1
      ]
    },
    "list": {
      "$id": "#/properties/list",
      "type": "array",
      "title": "The List Schema",
      "items": {
        "$id": "#/properties/list/items",
        "type": "object",
        "title": "The Items Schema",
        "required": [
          "dt",
          "main",
          "weather",
          "clouds",
          "wind",
          "sys",
          "dt_txt"
        ],
        "properties": {
          "dt": {
            "$id": "#/properties/list/items/properties/dt",
            "type": "integer",
            "title": "The Dt Schema",
            "default": 0,
            "examples": [
              1574175600
            ]
          },
          "main": {
            "$id": "#/properties/list/items/properties/main",
            "type": "object",
            "title": "The Main Schema",
            "required": [
              "temp",
              "temp_min",
              "temp_max",
              "pressure",
              "sea_level",
              "grnd_level",
              "humidity",
              "temp_kf"
            ],
            "properties": {
              "temp": {
                "$id": "#/properties/list/items/properties/main/properties/temp",
                "type": "number",
                "title": "The Temp Schema",
                "default": 0.0,
                "examples": [
                  274.93
                ]
              },
              "temp_min": {
                "$id": "#/properties/list/items/properties/main/properties/temp_min",
                "type": "number",
                "title": "The Temp_min Schema",
                "default": 0.0,
                "examples": [
                  274.93
                ]
              },
              "temp_max": {
                "$id": "#/properties/list/items/properties/main/properties/temp_max",
                "type": "number",
                "title": "The Temp_max Schema",
                "default": 0.0,
                "examples": [
                  275.23
                ]
              },
              "pressure": {
                "$id": "#/properties/list/items/properties/main/properties/pressure",
                "type": "integer",
                "title": "The Pressure Schema",
                "default": 0,
                "examples": [
                  1033
                ]
              },
              "sea_level": {
                "$id": "#/properties/list/items/properties/main/properties/sea_level",
                "type": "integer",
                "title": "The Sea_level Schema",
                "default": 0,
                "examples": [
                  1033
                ]
              },
              "grnd_level": {
                "$id": "#/properties/list/items/properties/main/properties/grnd_level",
                "type": "integer",
                "title": "The Grnd_level Schema",
                "default": 0,
                "examples": [
                  1012
                ]
              },
              "humidity": {
                "$id": "#/properties/list/items/properties/main/properties/humidity",
                "type": "integer",
                "title": "The Humidity Schema",
                "default": 0,
                "examples": [
                  87
                ]
              },
              "temp_kf": {
                "$id": "#/properties/list/items/properties/main/properties/temp_kf",
                "type": "number",
                "title": "The Temp_kf Schema",
                "default": 0.0,
                "examples": [
                  -0.3
                ]
              }
            }
          },
          "weather": {
            "$id": "#/properties/list/items/properties/weather",
            "type": "array",
            "title": "The Weather Schema",
            "items": {
              "$id": "#/properties/list/items/properties/weather/items",
              "type": "object",
              "title": "The Items Schema",
              "required": [
                "id",
                "main",
                "description",
                "icon"
              ],
              "properties": {
                "id": {
                  "$id": "#/properties/list/items/properties/weather/items/properties/id",
                  "type": "integer",
                  "title": "The Id Schema",
                  "default": 0,
                  "examples": [
                    804
                  ]
                },
                "main": {
                  "$id": "#/properties/list/items/properties/weather/items/properties/main",
                  "type": "string",
                  "title": "The Main Schema",
                  "default": "",
                  "examples": [
                    "Clouds"
                  ],
                  "pattern": "^(.*)$"
                },
                "description": {
                  "$id": "#/properties/list/items/properties/weather/items/properties/description",
                  "type": "string",
                  "title": "The Description Schema",
                  "default": "",
                  "examples": [
                    "overcast clouds"
                  ],
                  "pattern": "^(.*)$"
                },
                "icon": {
                  "$id": "#/properties/list/items/properties/weather/items/properties/icon",
                  "type": "string",
                  "title": "The Icon Schema",
                  "default": "",
                  "examples": [
                    "04n"
                  ],
                  "pattern": "^(.*)$"
                }
              }
            }
          },
          "clouds": {
            "$id": "#/properties/list/items/properties/clouds",
            "type": "object",
            "title": "The Clouds Schema",
            "required": [
              "all"
            ],
            "properties": {
              "all": {
                "$id": "#/properties/list/items/properties/clouds/properties/all",
                "type": "integer",
                "title": "The All Schema",
                "default": 0,
                "examples": [
                  96
                ]
              }
            }
          },
          "wind": {
            "$id": "#/properties/list/items/properties/wind",
            "type": "object",
            "title": "The Wind Schema",
            "required": [
              "speed",
              "deg"
            ],
            "properties": {
              "speed": {
                "$id": "#/properties/list/items/properties/wind/properties/speed",
                "type": "number",
                "title": "The Speed Schema",
                "default": 0.0,
                "examples": [
                  2.72
                ]
              },
              "deg": {
                "$id": "#/properties/list/items/properties/wind/properties/deg",
                "type": "integer",
                "title": "The Deg Schema",
                "default": 0,
                "examples": [
                  112
                ]
              }
            }
          },
          "sys": {
            "$id": "#/properties/list/items/properties/sys",
            "type": "object",
            "title": "The Sys Schema",
            "required": [
              "pod"
            ],
            "properties": {
              "pod": {
                "$id": "#/properties/list/items/properties/sys/properties/pod",
                "type": "string",
                "title": "The Pod Schema",
                "default": "",
                "examples": [
                  "n"
                ],
                "pattern": "^(.*)$"
              }
            }
          },
          "dt_txt": {
            "$id": "#/properties/list/items/properties/dt_txt",
            "type": "string",
            "title": "The Dt_txt Schema",
            "default": "",
            "examples": [
              "2019-11-19 15:00:00"
            ],
            "pattern": "^(.*)$"
          }
        }
      }
    },
    "city": {
      "$id": "#/properties/city",
      "type": "object",
      "title": "The City Schema",
      "required": [
        "id",
        "name",
        "coord",
        "country",
        "timezone",
        "sunrise",
        "sunset"
      ],
      "properties": {
        "id": {
          "$id": "#/properties/city/properties/id",
          "type": "integer",
          "title": "The Id Schema",
          "default": 0,
          "examples": [
            524901
          ]
        },
        "name": {
          "$id": "#/properties/city/properties/name",
          "type": "string",
          "title": "The Name Schema",
          "default": "",
          "examples": [
            "Moscow"
          ],
          "pattern": "^(.*)$"
        },
        "coord": {
          "$id": "#/properties/city/properties/coord",
          "type": "object",
          "title": "The Coord Schema",
          "required": [
            "lat",
            "lon"
          ],
          "properties": {
            "lat": {
              "$id": "#/properties/city/properties/coord/properties/lat",
              "type": "number",
              "title": "The Lat Schema",
              "default": 0.0,
              "examples": [
                55.7522
              ]
            },
            "lon": {
              "$id": "#/properties/city/properties/coord/properties/lon",
              "type": "number",
              "title": "The Lon Schema",
              "default": 0.0,
              "examples": [
                37.6156
              ]
            }
          }
        },
        "country": {
          "$id": "#/properties/city/properties/country",
          "type": "string",
          "title": "The Country Schema",
          "default": "",
          "examples": [
            "RU"
          ],
          "pattern": "^(.*)$"
        },
        "timezone": {
          "$id": "#/properties/city/properties/timezone",
          "type": "integer",
          "title": "The Timezone Schema",
          "default": 0,
          "examples": [
            10800
          ]
        },
        "sunrise": {
          "$id": "#/properties/city/properties/sunrise",
          "type": "integer",
          "title": "The Sunrise Schema",
          "default": 0,
          "examples": [
            1574140324
          ]
        },
        "sunset": {
          "$id": "#/properties/city/properties/sunset",
          "type": "integer",
          "title": "The Sunset Schema",
          "default": 0,
          "examples": [
            1574169472
          ]
        }
      }
    }
  }
}

=== BitFis/advanced-mobile-dev-fin/ex2/app/src/androidTest/assets/sydney_forecast_weather.json
{
  "cod": "200",
  "message": 0,
  "cnt": 40,
  "list": [
    {
      "dt": 1574197200,
      "main": {
        "temp": 18.41,
        "temp_min": 17.67,
        "temp_max": 18.41,
        "pressure": 1018,
        "sea_level": 1018,
        "grnd_level": 1008,
        "humidity": 70,
        "temp_kf": 0.74
      },
      "weather": [
        {
          "id": 500,
          "main": "Rain",
          "description": "light rain",
          "icon": "10n"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.36,
        "deg": 168
      },
      "rain": {
        "3h": 0.06
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2019-11-19 21:00:00"
    },
    {
      "dt": 1574208000,
      "main": {
        "temp": 20.51,
        "temp_min": 19.95,
        "temp_max": 20.51,
        "pressure": 1017,
        "sea_level": 1017,
        "grnd_level": 1008,
        "humidity": 59,
        "temp_kf": 0.56
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04d"
        }
      ],
      "clouds": {
        "all": 100
      },
      "wind": {
        "speed": 2.08,
        "deg": 121
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2019-11-20 00:00:00"
    },
    {
      "dt": 1574218800,
      "main": {
        "temp": 23.27,
        "temp_min": 22.9,
        "temp_max": 23.27,
        "pressure": 1016,
        "sea_level": 1016,
        "grnd_level": 1007,
        "humidity": 51,
        "temp_kf": 0.37
      },
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "clouds": {
        "all": 84
      },
      "wind": {
        "speed": 3.85,
        "deg": 98
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2019-11-20 03:00:00"
    },
    {
      "dt": 1574229600,
      "main": {
        "temp": 22.06,
        "temp_min": 21.87,
        "temp_max": 22.06,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1006,
        "humidity": 58,
        "temp_kf": 0.19
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 47
      },
      "wind": {
        "speed": 4.5,
        "deg": 96
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2019-11-20 06:00:00"
    },
    {
      "dt": 1574240400,
      "main": {
        "temp": 17.78,
        "temp_min": 17.78,
        "temp_max": 17.78,
        "pressure": 1017,
        "sea_level": 1017,
        "grnd_level": 1008,
        "humidity": 83,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ],
      "clouds": {
        "all": 27
      },
      "wind": {
        "speed": 1.98,
        "deg": 107
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2019-11-20 09:00:00"
    },
    {
      "dt": 1574251200,
      "main": {
        "temp": 17.04,
        "temp_min": 17.04,
        "temp_max": 17.04,
        "pressure": 1018,
        "sea_level": 1018,
        "grnd_level": 1009,
        "humidity": 90,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02n"
        }
      ],
      "clouds": {
        "all": 23
      },
      "wind": {
        "speed": 0.8,
        "deg": 334
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2019-11-20 12:00:00"
    },
    {
      "dt": 1574262000,
      "main": {
        "temp": 16.19,
        "temp_min": 16.19,
        "temp_max": 16.19,
        "pressure": 1016,
        "sea_level": 1016,
        "grnd_level": 1007,
        "humidity": 92,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03n"
        }
      ],
      "clouds": {
        "all": 37
      },
      "wind": {
        "speed": 1.86,
        "deg": 260
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2019-11-20 15:00:00"
    },
    {
      "dt": 1574272800,
      "main": {
        "temp": 15.85,
        "temp_min": 15.85,
        "temp_max": 15.85,
        "pressure": 1015,
        "sea_level": 1015,
        "grnd_level": 1006,
        "humidity": 92,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 801,
          "main": "Clouds",
          "description": "few clouds",
          "icon": "02n"
        }
      ],
      "clouds": {
        "all": 20
      },
      "wind": {
        "speed": 1.54,
        "deg": 298
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2019-11-20 18:00:00"
    },
    {
      "dt": 1574283600,
      "main": {
        "temp": 20.88,
        "temp_min": 20.88,
        "temp_max": 20.88,
        "pressure": 1016,
        "sea_level": 1016,
        "grnd_level": 1007,
        "humidity": 69,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 1.95,
        "deg": 346
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2019-11-20 21:00:00"
    },
    {
      "dt": 1574294400,
      "main": {
        "temp": 28.43,
        "temp_min": 28.43,
        "temp_max": 28.43,
        "pressure": 1014,
        "sea_level": 1014,
        "grnd_level": 1005,
        "humidity": 43,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 3.4,
        "deg": 39
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2019-11-21 00:00:00"
    },
    {
      "dt": 1574305200,
      "main": {
        "temp": 30.61,
        "temp_min": 30.61,
        "temp_max": 30.61,
        "pressure": 1011,
        "sea_level": 1011,
        "grnd_level": 1002,
        "humidity": 40,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04d"
        }
      ],
      "clouds": {
        "all": 70
      },
      "wind": {
        "speed": 5.58,
        "deg": 71
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2019-11-21 03:00:00"
    },
    {
      "dt": 1574316000,
      "main": {
        "temp": 27.47,
        "temp_min": 27.47,
        "temp_max": 27.47,
        "pressure": 1008,
        "sea_level": 1008,
        "grnd_level": 999,
        "humidity": 53,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 802,
          "main": "Clouds",
          "description": "scattered clouds",
          "icon": "03d"
        }
      ],
      "clouds": {
        "all": 35
      },
      "wind": {
        "speed": 6.07,
        "deg": 61
      },
      "sys": {
        "pod": "d"
      },
      "dt_txt": "2019-11-21 06:00:00"
    },
    {
      "dt": 1574326800,
      "main": {
        "temp": 22.62,
        "temp_min": 22.62,
        "temp_max": 22.62,
        "pressure": 1010,
        "sea_level": 1010,
        "grnd_level": 1000,
        "humidity": 68,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 0
      },
      "wind": {
        "speed": 2.52,
        "deg": 51
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2019-11-21 09:00:00"
    },
    {
      "dt": 1574337600,
      "main": {
        "temp": 21.6,
        "temp_min": 21.6,
        "temp_max": 21.6,
        "pressure": 1009,
        "sea_level": 1009,
        "grnd_level": 1000,
        "humidity": 71,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01n"
        }
      ],
      "clouds": {
        "all": 5
      },
      "wind": {
        "speed": 0.74,
        "deg": 344
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2019-11-21 12:00:00"
    },
    {
      "dt": 1574348400,
      "main": {
        "temp": 20.59,
        "temp_min": 20.59,
        "temp_max": 20.59,
        "pressure": 1008,
        "sea_level": 1008,
        "grnd_level": 999,
        "humidity": 75,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 803,
          "main": "Clouds",
          "description": "broken clouds",
          "icon": "04n"
        }
      ],
      "clouds": {
        "all": 74
      },
      "wind": {
        "speed": 1.06,
        "deg": 328
      },
      "sys": {
        "pod": "n"
      },
      "dt_txt": "2019-11-21 15:00:00"
    },
    {
      "dt": 1574359200,
      "main": {
        "temp": 20.56,
        "temp_min": 20.56,
        "temp_max": 20.56,
        "pressure": 1010,
        "sea_level": 1010,
        "grnd_level": 1000,
        "humidity": 64,
        "temp_kf": 0
      },
      "weather": [
        {
          "id": 804,
          "main": "Clouds",
          "description": "overcast clouds",
          "icon": "04n"
        }
      ],
      "clouds": {
        "all": 86
      },
      "wind": {
        "speed": 1.71,
        "deg": 300
      },
      "sys": {
        "pod": "n"
      },
